baseURL = 'https://aolufisayo.com'
languageCode = 'en-us'
title = 'aolufisayo'
theme = ["PaperMod"]
enableEmoji = true
publishDir = "docs"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 20
  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/archive/"
    weight = 30
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 40
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 50